### ISSUE TITLE
MS Store link links to the homepage

### ISSUE THREAD

**Issue by TechStudent11** [torchgm/NewModernWinver#1]
It links to https://microsoft.com not the app link.

**Comment by Erisa** [comment]
Yes because there is no Microsoft Store link yet, that's used as a placeholder.

**Comment by TechStudent11** [comment]
Makes sense. I'll close this when that's fixed.

**Comment by torchgm** [comment]
The Microsoft Partner Team required this repo to be public because the app links to it, hence why it's, well, public. If I could have my own way it'd've stayed private until it was approved for release on the Microsoft Store.

**Comment by TechStudent11** [comment]
Ah okay

**Comment by TechStudent11** [comment]
MS Store link is now here: https://www.microsoft.com/p/ModernWinver/9ND14WHFRGSX

Closing...
