### ISSUE TITLE
Feature request: Show OS build

### ISSUE THREAD

**Issue by maicol07** [torchgm/NewModernWinver#2]
Example on Dev channel:
![immagine](https://user-images.githubusercontent.com/9463142/152418584-cf1f26b8-9c23-4855-b242-f9c6a5dc2615.png)

Standard winver:
![immagine](https://user-images.githubusercontent.com/9463142/152418626-0222679e-638c-497b-83ae-695856aaf44e.png)

**Comment by Erisa** [comment]
What information do you want added? Your build is 22543.1000 and that shows in both screenshots.

**Comment by maicol07** [comment]
Just saw the build is below "Installed on" 😅

**Comment by maicol07** [comment]
Maybe it is better if it's next to `Dev`

**Comment by Erisa** [comment]
It's sorted the same as Settings > System > About
![image](https://user-images.githubusercontent.com/14004943/152418942-c2064f65-8b21-4f63-9857-1cd78d98c36d.png)

So I think it's fine as-is.

**Comment by maicol07** [comment]
Oh ok, that's fine. Sorry for the issue! :sweat:
