### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by OmarProGamer98** [torchgm/NewModernWinver#3]
Hi the command mwv not works on windows 10 can you fix this please here are the image
![image](https://user-images.githubusercontent.com/88203855/153912037-6080af5f-62df-43a7-88e9-617b8ca78830.png)
![image](https://user-images.githubusercontent.com/88203855/153912240-2b803912-6d4d-4e81-9d48-f9f494f6023d.png)

**Comment by Erisa** [comment]
You need a colon after it, so `mwv:`

**Comment by OmarProGamer98** [comment]
> You need a colon after it, so `mwv:`

Ooh on thanks a lot
